# Generated by Django 3.0.8 on 2020-08-27 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sondage_title', models.CharField(max_length=300)),
                ('propostion_nom', models.CharField(max_length=300)),
                ('sondage_content', models.TextField()),
                ('vote_yes', models.IntegerField(default=0)),
                ('vote_no', models.IntegerField(default=0)),
                ('vote_null', models.IntegerField(default=0)),
                ('sondage_image', models.ImageField(upload_to='sondage_img/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sondageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondage.Sondage')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
