# Generated by Django 3.0.8 on 2020-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actu_title', models.CharField(max_length=300)),
                ('propostion_nom', models.CharField(max_length=300)),
                ('actu_content', models.TextField()),
                ('actu_image', models.ImageField(upload_to='actu_img/')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
