# Generated by Django 3.0.8 on 2020-08-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='actu_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
