# Generated by Django 3.0.8 on 2020-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0002_auto_20200824_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='actu_image',
            field=models.ImageField(upload_to='actu_img/'),
        ),
    ]
